/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--arc-color-primary-50)',
          100: 'var(--arc-color-primary-100)',
          200: 'var(--arc-color-primary-200)',
          300: 'var(--arc-color-primary-300)',
          400: 'var(--arc-color-primary-400)',
          500: 'var(--arc-color-primary-500)',
          600: 'var(--arc-color-primary-600)',
          700: 'var(--arc-color-primary-700)',
          800: 'var(--arc-color-primary-800)',
          900: 'var(--arc-color-primary-900)',
          DEFAULT: 'var(--arc-color-primary-500)',
        },
        secondary: {
          50: 'var(--arc-color-secondary-50)',
          100: 'var(--arc-color-secondary-100)',
          200: 'var(--arc-color-secondary-200)',
          300: 'var(--arc-color-secondary-300)',
          400: 'var(--arc-color-secondary-400)',
          500: 'var(--arc-color-secondary-500)',
          600: 'var(--arc-color-secondary-600)',
          700: 'var(--arc-color-secondary-700)',
          800: 'var(--arc-color-secondary-800)',
          900: 'var(--arc-color-secondary-900)',
          DEFAULT: 'var(--arc-color-secondary-500)',
        },
        neutral: {
          0: 'var(--arc-color-neutral-0)',
          50: 'var(--arc-color-neutral-50)',
          100: 'var(--arc-color-neutral-100)',
          200: 'var(--arc-color-neutral-200)',
          300: 'var(--arc-color-neutral-300)',
          400: 'var(--arc-color-neutral-400)',
          500: 'var(--arc-color-neutral-500)',
          600: 'var(--arc-color-neutral-600)',
          700: 'var(--arc-color-neutral-700)',
          800: 'var(--arc-color-neutral-800)',
          900: 'var(--arc-color-neutral-900)',
          950: 'var(--arc-color-neutral-950)',
        },
        success: {
          50: 'var(--arc-color-success-50)',
          500: 'var(--arc-color-success-500)',
          700: 'var(--arc-color-success-700)',
          DEFAULT: 'var(--arc-color-success-500)',
        },
        warning: {
          50: 'var(--arc-color-warning-50)',
          500: 'var(--arc-color-warning-500)',
          700: 'var(--arc-color-warning-700)',
          DEFAULT: 'var(--arc-color-warning-500)',
        },
        error: {
          50: 'var(--arc-color-error-50)',
          500: 'var(--arc-color-error-500)',
          700: 'var(--arc-color-error-700)',
          DEFAULT: 'var(--arc-color-error-500)',
        },
        info: {
          50: 'var(--arc-color-info-50)',
          500: 'var(--arc-color-info-500)',
          700: 'var(--arc-color-info-700)',
          DEFAULT: 'var(--arc-color-info-500)',
        },
      },
      spacing: {
        'arc-1': 'var(--arc-spacing-1)',
        'arc-2': 'var(--arc-spacing-2)',
        'arc-3': 'var(--arc-spacing-3)',
        'arc-4': 'var(--arc-spacing-4)',
        'arc-5': 'var(--arc-spacing-5)',
        'arc-6': 'var(--arc-spacing-6)',
        'arc-8': 'var(--arc-spacing-8)',
        'arc-10': 'var(--arc-spacing-10)',
        'arc-12': 'var(--arc-spacing-12)',
        'arc-16': 'var(--arc-spacing-16)',
      },
      borderRadius: {
        'arc-sm': 'var(--arc-border-radius-sm)',
        'arc-md': 'var(--arc-border-radius-md)',
        'arc-lg': 'var(--arc-border-radius-lg)',
        'arc-xl': 'var(--arc-border-radius-xl)',
        'arc-full': 'var(--arc-border-radius-full)',
      },
      fontSize: {
        'arc-xs': 'var(--arc-font-size-xs)',
        'arc-sm': 'var(--arc-font-size-sm)',
        'arc-base': 'var(--arc-font-size-base)',
        'arc-lg': 'var(--arc-font-size-lg)',
        'arc-xl': 'var(--arc-font-size-xl)',
        'arc-2xl': 'var(--arc-font-size-2xl)',
        'arc-3xl': 'var(--arc-font-size-3xl)',
        'arc-4xl': 'var(--arc-font-size-4xl)',
      },
      fontFamily: {
        sans: 'var(--arc-font-family-sans)',
        mono: 'var(--arc-font-family-mono)',
      },
      boxShadow: {
        'arc-sm': 'var(--arc-shadow-sm)',
        'arc-md': 'var(--arc-shadow-md)',
        'arc-lg': 'var(--arc-shadow-lg)',
        'arc-xl': 'var(--arc-shadow-xl)',
      },
    },
  },
};
