/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ArcAlert {
        "alertTitle"?: string;
        /**
          * @default false
         */
        "dismissible": boolean;
        /**
          * @default true
         */
        "icon": boolean;
        /**
          * @default 'info'
         */
        "variant": 'info' | 'success' | 'warning' | 'error';
        /**
          * Whether the alert is visible. Set to false to programmatically dismiss, or back to true to restore.
          * @default true
         */
        "visible": boolean;
    }
    interface ArcAvatar {
        /**
          * @default ''
         */
        "alt": string;
        /**
          * @default ''
         */
        "name": string;
        /**
          * @default 'circle'
         */
        "shape": 'circle' | 'square';
        /**
          * @default 'md'
         */
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * @default ''
         */
        "src": string;
    }
    interface ArcBadge {
        /**
          * Show a dot indicator instead of content
          * @default false
         */
        "dot": boolean;
        /**
          * Use pill (fully rounded) shape
          * @default true
         */
        "pill": boolean;
        /**
          * Badge size
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * Color variant
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | 'neutral';
    }
    interface ArcButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Whether the button is in a loading state
          * @default false
         */
        "loading": boolean;
        /**
          * Button size
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * HTML button type attribute
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style variant
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive';
    }
    interface ArcCard {
        /**
          * Whether the card is interactive/clickable
          * @default false
         */
        "clickable": boolean;
        /**
          * Inner padding size
          * @default 'md'
         */
        "padding": 'none' | 'sm' | 'md' | 'lg';
        /**
          * Visual style variant
          * @default 'default'
         */
        "variant": 'default' | 'elevated' | 'outlined';
    }
    interface ArcIcon {
        /**
          * Stroke color
          * @default 'currentColor'
         */
        "color": string;
        /**
          * Name of the icon to render
          * @default ''
         */
        "name": string;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size": number;
        /**
          * Stroke width
          * @default 2
         */
        "strokeWidth": number;
    }
    interface ArcInput {
        /**
          * @default false
         */
        "disabled": boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        "label"?: string;
        "name"?: string;
        /**
          * @default ''
         */
        "placeholder": string;
        /**
          * @default false
         */
        "required": boolean;
        /**
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * @default 'text'
         */
        "type": 'text' | 'email' | 'password' | 'search' | 'number' | 'tel' | 'url';
        /**
          * @default ''
         */
        "value": string;
    }
    interface ArcModal {
        /**
          * Whether pressing Escape closes the modal
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Whether clicking the overlay closes the modal
          * @default true
         */
        "closeOnOverlay": boolean;
        /**
          * Programmatically hide the modal
         */
        "hide": () => Promise<void>;
        /**
          * Whether the modal is open
          * @default false
         */
        "open": boolean;
        /**
          * Programmatically show the modal
         */
        "show": () => Promise<void>;
        /**
          * Modal size variant
          * @default 'md'
         */
        "size": 'sm' | 'md' | 'lg' | 'full';
    }
    interface ArcThemeProvider {
        /**
          * Theme mode: 'light', 'dark', or 'system' (follows OS preference)
          * @default 'system'
         */
        "theme": 'light' | 'dark' | 'system';
    }
    interface ArcTooltip {
        /**
          * Text content displayed in the tooltip
          * @default ''
         */
        "content": string;
        /**
          * Delay in ms before showing the tooltip
          * @default 200
         */
        "delay": number;
        /**
          * Position of the tooltip relative to the trigger
          * @default 'top'
         */
        "position": 'top' | 'right' | 'bottom' | 'left';
    }
}
export interface ArcAlertCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcAlertElement;
}
export interface ArcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcButtonElement;
}
export interface ArcInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcInputElement;
}
export interface ArcModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcModalElement;
}
declare global {
    interface HTMLArcAlertElementEventMap {
        "arcDismiss": void;
    }
    interface HTMLArcAlertElement extends Components.ArcAlert, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArcAlertElementEventMap>(type: K, listener: (this: HTMLArcAlertElement, ev: ArcAlertCustomEvent<HTMLArcAlertElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArcAlertElementEventMap>(type: K, listener: (this: HTMLArcAlertElement, ev: ArcAlertCustomEvent<HTMLArcAlertElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArcAlertElement: {
        prototype: HTMLArcAlertElement;
        new (): HTMLArcAlertElement;
    };
    interface HTMLArcAvatarElement extends Components.ArcAvatar, HTMLStencilElement {
    }
    var HTMLArcAvatarElement: {
        prototype: HTMLArcAvatarElement;
        new (): HTMLArcAvatarElement;
    };
    interface HTMLArcBadgeElement extends Components.ArcBadge, HTMLStencilElement {
    }
    var HTMLArcBadgeElement: {
        prototype: HTMLArcBadgeElement;
        new (): HTMLArcBadgeElement;
    };
    interface HTMLArcButtonElementEventMap {
        "arcClick": void;
    }
    interface HTMLArcButtonElement extends Components.ArcButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArcButtonElementEventMap>(type: K, listener: (this: HTMLArcButtonElement, ev: ArcButtonCustomEvent<HTMLArcButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArcButtonElementEventMap>(type: K, listener: (this: HTMLArcButtonElement, ev: ArcButtonCustomEvent<HTMLArcButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArcButtonElement: {
        prototype: HTMLArcButtonElement;
        new (): HTMLArcButtonElement;
    };
    interface HTMLArcCardElement extends Components.ArcCard, HTMLStencilElement {
    }
    var HTMLArcCardElement: {
        prototype: HTMLArcCardElement;
        new (): HTMLArcCardElement;
    };
    interface HTMLArcIconElement extends Components.ArcIcon, HTMLStencilElement {
    }
    var HTMLArcIconElement: {
        prototype: HTMLArcIconElement;
        new (): HTMLArcIconElement;
    };
    interface HTMLArcInputElementEventMap {
        "arcInput": string;
        "arcChange": string;
        "arcFocus": void;
        "arcBlur": void;
    }
    interface HTMLArcInputElement extends Components.ArcInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArcInputElementEventMap>(type: K, listener: (this: HTMLArcInputElement, ev: ArcInputCustomEvent<HTMLArcInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArcInputElementEventMap>(type: K, listener: (this: HTMLArcInputElement, ev: ArcInputCustomEvent<HTMLArcInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArcInputElement: {
        prototype: HTMLArcInputElement;
        new (): HTMLArcInputElement;
    };
    interface HTMLArcModalElementEventMap {
        "arcClose": void;
    }
    interface HTMLArcModalElement extends Components.ArcModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLArcModalElementEventMap>(type: K, listener: (this: HTMLArcModalElement, ev: ArcModalCustomEvent<HTMLArcModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLArcModalElementEventMap>(type: K, listener: (this: HTMLArcModalElement, ev: ArcModalCustomEvent<HTMLArcModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLArcModalElement: {
        prototype: HTMLArcModalElement;
        new (): HTMLArcModalElement;
    };
    interface HTMLArcThemeProviderElement extends Components.ArcThemeProvider, HTMLStencilElement {
    }
    var HTMLArcThemeProviderElement: {
        prototype: HTMLArcThemeProviderElement;
        new (): HTMLArcThemeProviderElement;
    };
    interface HTMLArcTooltipElement extends Components.ArcTooltip, HTMLStencilElement {
    }
    var HTMLArcTooltipElement: {
        prototype: HTMLArcTooltipElement;
        new (): HTMLArcTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "arc-alert": HTMLArcAlertElement;
        "arc-avatar": HTMLArcAvatarElement;
        "arc-badge": HTMLArcBadgeElement;
        "arc-button": HTMLArcButtonElement;
        "arc-card": HTMLArcCardElement;
        "arc-icon": HTMLArcIconElement;
        "arc-input": HTMLArcInputElement;
        "arc-modal": HTMLArcModalElement;
        "arc-theme-provider": HTMLArcThemeProviderElement;
        "arc-tooltip": HTMLArcTooltipElement;
    }
}
declare namespace LocalJSX {
    interface ArcAlert {
        "alertTitle"?: string;
        /**
          * @default false
         */
        "dismissible"?: boolean;
        /**
          * @default true
         */
        "icon"?: boolean;
        "onArcDismiss"?: (event: ArcAlertCustomEvent<void>) => void;
        /**
          * @default 'info'
         */
        "variant"?: 'info' | 'success' | 'warning' | 'error';
        /**
          * Whether the alert is visible. Set to false to programmatically dismiss, or back to true to restore.
          * @default true
         */
        "visible"?: boolean;
    }
    interface ArcAvatar {
        /**
          * @default ''
         */
        "alt"?: string;
        /**
          * @default ''
         */
        "name"?: string;
        /**
          * @default 'circle'
         */
        "shape"?: 'circle' | 'square';
        /**
          * @default 'md'
         */
        "size"?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        /**
          * @default ''
         */
        "src"?: string;
    }
    interface ArcBadge {
        /**
          * Show a dot indicator instead of content
          * @default false
         */
        "dot"?: boolean;
        /**
          * Use pill (fully rounded) shape
          * @default true
         */
        "pill"?: boolean;
        /**
          * Badge size
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * Color variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | 'neutral';
    }
    interface ArcButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Whether the button is in a loading state
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted when the button is clicked (not emitted when disabled or loading)
         */
        "onArcClick"?: (event: ArcButtonCustomEvent<void>) => void;
        /**
          * Button size
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * HTML button type attribute
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style variant
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive';
    }
    interface ArcCard {
        /**
          * Whether the card is interactive/clickable
          * @default false
         */
        "clickable"?: boolean;
        /**
          * Inner padding size
          * @default 'md'
         */
        "padding"?: 'none' | 'sm' | 'md' | 'lg';
        /**
          * Visual style variant
          * @default 'default'
         */
        "variant"?: 'default' | 'elevated' | 'outlined';
    }
    interface ArcIcon {
        /**
          * Stroke color
          * @default 'currentColor'
         */
        "color"?: string;
        /**
          * Name of the icon to render
          * @default ''
         */
        "name"?: string;
        /**
          * Size of the icon in pixels
          * @default 24
         */
        "size"?: number;
        /**
          * Stroke width
          * @default 2
         */
        "strokeWidth"?: number;
    }
    interface ArcInput {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "errorMessage"?: string;
        "helperText"?: string;
        "label"?: string;
        "name"?: string;
        "onArcBlur"?: (event: ArcInputCustomEvent<void>) => void;
        "onArcChange"?: (event: ArcInputCustomEvent<string>) => void;
        "onArcFocus"?: (event: ArcInputCustomEvent<void>) => void;
        "onArcInput"?: (event: ArcInputCustomEvent<string>) => void;
        /**
          * @default ''
         */
        "placeholder"?: string;
        /**
          * @default false
         */
        "required"?: boolean;
        /**
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * @default 'text'
         */
        "type"?: 'text' | 'email' | 'password' | 'search' | 'number' | 'tel' | 'url';
        /**
          * @default ''
         */
        "value"?: string;
    }
    interface ArcModal {
        /**
          * Whether pressing Escape closes the modal
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Whether clicking the overlay closes the modal
          * @default true
         */
        "closeOnOverlay"?: boolean;
        /**
          * Emitted when the modal requests to be closed
         */
        "onArcClose"?: (event: ArcModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open
          * @default false
         */
        "open"?: boolean;
        /**
          * Modal size variant
          * @default 'md'
         */
        "size"?: 'sm' | 'md' | 'lg' | 'full';
    }
    interface ArcThemeProvider {
        /**
          * Theme mode: 'light', 'dark', or 'system' (follows OS preference)
          * @default 'system'
         */
        "theme"?: 'light' | 'dark' | 'system';
    }
    interface ArcTooltip {
        /**
          * Text content displayed in the tooltip
          * @default ''
         */
        "content"?: string;
        /**
          * Delay in ms before showing the tooltip
          * @default 200
         */
        "delay"?: number;
        /**
          * Position of the tooltip relative to the trigger
          * @default 'top'
         */
        "position"?: 'top' | 'right' | 'bottom' | 'left';
    }

    interface ArcAlertAttributes {
        "variant": 'info' | 'success' | 'warning' | 'error';
        "alertTitle": string;
        "dismissible": boolean;
        "icon": boolean;
        "visible": boolean;
    }
    interface ArcAvatarAttributes {
        "src": string;
        "alt": string;
        "name": string;
        "size": 'xs' | 'sm' | 'md' | 'lg' | 'xl';
        "shape": 'circle' | 'square';
    }
    interface ArcBadgeAttributes {
        "variant": 'primary' | 'secondary' | 'success' | 'warning' | 'error' | 'info' | 'neutral';
        "size": 'sm' | 'md' | 'lg';
        "dot": boolean;
        "pill": boolean;
    }
    interface ArcButtonAttributes {
        "variant": 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive';
        "size": 'sm' | 'md' | 'lg';
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "loading": boolean;
    }
    interface ArcCardAttributes {
        "variant": 'default' | 'elevated' | 'outlined';
        "padding": 'none' | 'sm' | 'md' | 'lg';
        "clickable": boolean;
    }
    interface ArcIconAttributes {
        "name": string;
        "size": number;
        "color": string;
        "strokeWidth": number;
    }
    interface ArcInputAttributes {
        "type": 'text' | 'email' | 'password' | 'search' | 'number' | 'tel' | 'url';
        "value": string;
        "placeholder": string;
        "label": string;
        "helperText": string;
        "errorMessage": string;
        "disabled": boolean;
        "required": boolean;
        "size": 'sm' | 'md' | 'lg';
        "name": string;
    }
    interface ArcModalAttributes {
        "open": boolean;
        "size": 'sm' | 'md' | 'lg' | 'full';
        "closeOnOverlay": boolean;
        "closeOnEscape": boolean;
    }
    interface ArcThemeProviderAttributes {
        "theme": 'light' | 'dark' | 'system';
    }
    interface ArcTooltipAttributes {
        "content": string;
        "position": 'top' | 'right' | 'bottom' | 'left';
        "delay": number;
    }

    interface IntrinsicElements {
        "arc-alert": Omit<ArcAlert, keyof ArcAlertAttributes> & { [K in keyof ArcAlert & keyof ArcAlertAttributes]?: ArcAlert[K] } & { [K in keyof ArcAlert & keyof ArcAlertAttributes as `attr:${K}`]?: ArcAlertAttributes[K] } & { [K in keyof ArcAlert & keyof ArcAlertAttributes as `prop:${K}`]?: ArcAlert[K] };
        "arc-avatar": Omit<ArcAvatar, keyof ArcAvatarAttributes> & { [K in keyof ArcAvatar & keyof ArcAvatarAttributes]?: ArcAvatar[K] } & { [K in keyof ArcAvatar & keyof ArcAvatarAttributes as `attr:${K}`]?: ArcAvatarAttributes[K] } & { [K in keyof ArcAvatar & keyof ArcAvatarAttributes as `prop:${K}`]?: ArcAvatar[K] };
        "arc-badge": Omit<ArcBadge, keyof ArcBadgeAttributes> & { [K in keyof ArcBadge & keyof ArcBadgeAttributes]?: ArcBadge[K] } & { [K in keyof ArcBadge & keyof ArcBadgeAttributes as `attr:${K}`]?: ArcBadgeAttributes[K] } & { [K in keyof ArcBadge & keyof ArcBadgeAttributes as `prop:${K}`]?: ArcBadge[K] };
        "arc-button": Omit<ArcButton, keyof ArcButtonAttributes> & { [K in keyof ArcButton & keyof ArcButtonAttributes]?: ArcButton[K] } & { [K in keyof ArcButton & keyof ArcButtonAttributes as `attr:${K}`]?: ArcButtonAttributes[K] } & { [K in keyof ArcButton & keyof ArcButtonAttributes as `prop:${K}`]?: ArcButton[K] };
        "arc-card": Omit<ArcCard, keyof ArcCardAttributes> & { [K in keyof ArcCard & keyof ArcCardAttributes]?: ArcCard[K] } & { [K in keyof ArcCard & keyof ArcCardAttributes as `attr:${K}`]?: ArcCardAttributes[K] } & { [K in keyof ArcCard & keyof ArcCardAttributes as `prop:${K}`]?: ArcCard[K] };
        "arc-icon": Omit<ArcIcon, keyof ArcIconAttributes> & { [K in keyof ArcIcon & keyof ArcIconAttributes]?: ArcIcon[K] } & { [K in keyof ArcIcon & keyof ArcIconAttributes as `attr:${K}`]?: ArcIconAttributes[K] } & { [K in keyof ArcIcon & keyof ArcIconAttributes as `prop:${K}`]?: ArcIcon[K] };
        "arc-input": Omit<ArcInput, keyof ArcInputAttributes> & { [K in keyof ArcInput & keyof ArcInputAttributes]?: ArcInput[K] } & { [K in keyof ArcInput & keyof ArcInputAttributes as `attr:${K}`]?: ArcInputAttributes[K] } & { [K in keyof ArcInput & keyof ArcInputAttributes as `prop:${K}`]?: ArcInput[K] };
        "arc-modal": Omit<ArcModal, keyof ArcModalAttributes> & { [K in keyof ArcModal & keyof ArcModalAttributes]?: ArcModal[K] } & { [K in keyof ArcModal & keyof ArcModalAttributes as `attr:${K}`]?: ArcModalAttributes[K] } & { [K in keyof ArcModal & keyof ArcModalAttributes as `prop:${K}`]?: ArcModal[K] };
        "arc-theme-provider": Omit<ArcThemeProvider, keyof ArcThemeProviderAttributes> & { [K in keyof ArcThemeProvider & keyof ArcThemeProviderAttributes]?: ArcThemeProvider[K] } & { [K in keyof ArcThemeProvider & keyof ArcThemeProviderAttributes as `attr:${K}`]?: ArcThemeProviderAttributes[K] } & { [K in keyof ArcThemeProvider & keyof ArcThemeProviderAttributes as `prop:${K}`]?: ArcThemeProvider[K] };
        "arc-tooltip": Omit<ArcTooltip, keyof ArcTooltipAttributes> & { [K in keyof ArcTooltip & keyof ArcTooltipAttributes]?: ArcTooltip[K] } & { [K in keyof ArcTooltip & keyof ArcTooltipAttributes as `attr:${K}`]?: ArcTooltipAttributes[K] } & { [K in keyof ArcTooltip & keyof ArcTooltipAttributes as `prop:${K}`]?: ArcTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arc-alert": LocalJSX.IntrinsicElements["arc-alert"] & JSXBase.HTMLAttributes<HTMLArcAlertElement>;
            "arc-avatar": LocalJSX.IntrinsicElements["arc-avatar"] & JSXBase.HTMLAttributes<HTMLArcAvatarElement>;
            "arc-badge": LocalJSX.IntrinsicElements["arc-badge"] & JSXBase.HTMLAttributes<HTMLArcBadgeElement>;
            "arc-button": LocalJSX.IntrinsicElements["arc-button"] & JSXBase.HTMLAttributes<HTMLArcButtonElement>;
            "arc-card": LocalJSX.IntrinsicElements["arc-card"] & JSXBase.HTMLAttributes<HTMLArcCardElement>;
            "arc-icon": LocalJSX.IntrinsicElements["arc-icon"] & JSXBase.HTMLAttributes<HTMLArcIconElement>;
            "arc-input": LocalJSX.IntrinsicElements["arc-input"] & JSXBase.HTMLAttributes<HTMLArcInputElement>;
            "arc-modal": LocalJSX.IntrinsicElements["arc-modal"] & JSXBase.HTMLAttributes<HTMLArcModalElement>;
            "arc-theme-provider": LocalJSX.IntrinsicElements["arc-theme-provider"] & JSXBase.HTMLAttributes<HTMLArcThemeProviderElement>;
            "arc-tooltip": LocalJSX.IntrinsicElements["arc-tooltip"] & JSXBase.HTMLAttributes<HTMLArcTooltipElement>;
        }
    }
}
